aio-libs/aiohttp-session

.travis.yml

use the new docker based travis infrastructure by using the build in redis server

new travis build config

---

docs/index.rst
docs/reference.rst

[docs] RedisCookieStorage references to a non-existing object.

---

.travis.yml
aiohttp_session/nacl_storage.py
docs/conf.py
docs/glossary.rst
docs/reference.rst
requirements-dev.txt
setup.py
tests/test_nacl_storage.py

This code adds cookie storage based on nacl.secret.SecretBox https://pynacl.readthedocs.org/en/latest/secret/

Add optional NaCl encrypted storage

---

aiohttp_session/cookie_storage.py
tests/test_encrypted_cookie_storage.py

Handles cryptography.fernet.InvalidToken exception

---

aiohttp_session/__init__.py
tests/test_abstract_storage.py

Add expires field automatically to support older browsers

---

aiohttp_session/__init__.py
aiohttp_session/cookie_storage.py
aiohttp_session/nacl_storage.py
aiohttp_session/redis_storage.py
tests/test_redis_storage.py

Respect session.max_age in redis storage

---

aiohttp_session/__init__.py
tests/test_abstract_storage.py

This may be too simplistic as I don't understand why the monotonic clock is being used: It works in my case so I'll suggest it.

fixes #81, monotonic clock does not give a reasonable current time

---

docs/index.rst

https://github.com/aio-libs/aiohttp-session/issues/85

add info about redis key inside the doc

---

.travis.yml

for more info see https://github.com/KeepSafe/aiohttp/issues/1485

Fix cookie bug

---

README.rst

Add some labels

---

aiohttp_session/redis_storage.py
tests/test_redis_storage.py

[Redis] Return expired cookie on session.invalidate

---

aiohttp_session/redis_storage.py
tests/test_redis_storage.py

Add key_factory attr for redis_storage

---

aiohttp_session/__init__.py
setup.py
tests/test_response_types.py

Use new-style (decorated) middleware syntax

---

demo/redis_storage.py

Adding demo with using redis storage

---

.travis.yml
aiohttp_session/memcached_storage.py
demo/memcached_storage.py
docs/conf.py
docs/glossary.rst
requirements-dev.txt
setup.py
tests/test_memcached_storage.py

I added mamcached storage based on redis storage code.
Please check it.

Add memcached storage

---

aiohttp_session/__init__.py
docs/reference.rst
tests/test_session_dict.py

Method set_new_identity for change identity

---

setup.py

The same as for aiohttp-security in the commit 
https://github.com/aio-libs/aiohttp-security/commit/797d892ac123061dd92a70111e5aea7487973313

fix setup to read version on windows.

---

.travis.yml
docs/index.rst

Add _current version_ variable to index.rst

---

aiohttp_session/cookie_storage.py
tests/test_encrypted_cookie_storage.py

A few flake8 errors were introduced in #326 (mainly related to line length). Sorry for this.

Fix flake8 errors introduced by #326

---

docs/reference.rst

docs fix
documents only
* Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

Adding missing parenthesis

---

docs/index.rst

Fix the bug tracker link in README

---

docs/reference.rst

Fix typo in doc
No
No
* Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

Fix typos in reference.rst

---

aiohttp_session/__init__.py
tests/test_abstract_storage.py

Fix session resetting before expiry.

---

.pre-commit-config.yaml
README.rst
pytest.ini
tests/test_encrypted_cookie_storage.py

Fixes the configuration to run tests locally.
No.
#751
* Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

test setup adjustment

---

.mypy.ini
Makefile
README.rst
aiohttp_session/redis_storage.py
demo/redis_storage.py
docs/conf.py
docs/glossary.rst
docs/index.rst
docs/reference.rst
requirements-dev.txt
tests/test_redis_storage.py

Updated documentation for redis module
No.
#760
* Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

Updated documentation for redis module

---

demo/flash_messages_example.py
demo/login_required_example.py
requirements.txt

Edited the login_required example, the rest does not seem to need any changes

Update examples for aiohttp 3.9
