docs/reference.rst
Current code snippet misses the ``aiohttp_session.session_middleware`` wrapper, which leads to AssertionError when one tries to copy-paste-run it.
=> Add missing steps to the session redis storage example

README.rst, docs/conf.py, docs/glossary.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs link for their .org -> .io migration for hosted projects

README.rst, demo/main.py
* secret_key must be 32 url-safe base64-encoded bytes instead of 16 bytes
* using web.run_app(app) to follow aiohttp demo example
* added demo code
Run main.py in demo 
#32 
- [ O ] Code is written and well
- [ X ] Tests for the changes are provided (not required)
- [ O ] Documentation reflects the changes
=> Updated secret_key requirement in README.rst

README.rst
The title and commit diff says it all :) It's always a turn-off for me when a project's README has spelling errors.
=> README: fix spelling in part about redis sessions

docs/conf.py, docs/reference.rst
Also fix doc building issue due to NameError on alabaster
=> Fix #214 - docs should refer to JSON not pickle

.travis.yml, aiohttp_session/__init__.py, aiohttp_session/cookie_storage.py, aiohttp_session/memcached_storage.py, aiohttp_session/nacl_storage.py, aiohttp_session/redis_storage.py, demo/redis_storage.py, docs/index.rst, requirements-dev.txt, setup.py, tests/conftest.py, tests/test_abstract_storage.py, tests/test_cookie_storage.py, tests/test_encrypted_cookie_storage.py, tests/test_get_session.py, tests/test_http_exception.py, tests/test_memcached_storage.py, tests/test_nacl_storage.py, tests/test_path_domain.py, tests/test_redis_storage.py, tests/test_response_types.py
Drops support for Python<3.5.3
Drops support for aioredis<1.0.0
Caveats:
* The reason support for aioredis<1.0.0 was dropped:
* create_pool returns a `ConnectionsPool` object
* when `ConnectionsPool` is used with context management returns a `RedisConnection` object
* `RedisConnection` doesn't have `set` / `get` methods in v1.0.0+
* create_redis_pool (introduced in v1.0.0 ) returns a `Redis` object that wrapps `ConnectionsPool`
* when `Redis` is used whith context management returns a `ContextRedis` object that has `set` / `get`
My initial idea was to check whether the supplied pool was `ConnectionsPool` or `Redis` and in the first case wrap it:
```py
if isinstance(redis_pool, aioredis.pool.ConnectionsPool):
redis_pool = aioredis.commands.Redis(redis_pool)
elif not isinstance(redis_pool, …
```
=> New async/await syntax and aioredis 1.0.0 compatibility

aiohttp_session/__init__.py
Found when I was trying to add session data to home-assistant.
Mildly related to https://github.com/home-assistant/home-assistant/pull/12078.
=> Fixed the formatting of an error handling bad middleware return types.

setup.py
I was just testing a change to a library using aiohttp-session and realised that I was able to install aiohttp-session v2 into a python3.4 environment.
Adding the python_requires metadata prevents this from happening.
See also:
* https://stackoverflow.com/a/45362425/741316
* http://www.python3statement.org/practicalities/
* The docs at http://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords
=> Added the minimum python version into setup.py.

aiohttp_session/__init__.py, aiohttp_session/cookie_storage.py, aiohttp_session/memcached_storage.py, aiohttp_session/nacl_storage.py, aiohttp_session/redis_storage.py, docs/reference.rst, tests/conftest.py
I left the args explicit, means that json still needs to be imported in all files. The first solution using kwargs seemed kind of odd considering we're passing through everything else explicitly.
I didn't really look into it much but I couldn't get all tests to run because docker seems to be having hiccups at some point. Not sure if MacOS might be the culprit here.
About the docs, :class:`func` doesn't seem right but I'm new to Sphinx docs and couldn't get :func: parameters to work.
=> Move encoder and decoder to AbstractStorage

demo/flash_messages_example.py
We have an issue https://github.com/aio-libs/aiohttp-session/issues/25 for message flashing. I'm not sure what will be the final decision on that but we can at least include the snippet to the examples for users to refer when implementing such a feature in their application.
=> Flash messages example

aiohttp_session/__init__.py, aiohttp_session/redis_storage.py, tests/test_encrypted_cookie_storage.py, tests/test_memcached_storage.py, tests/test_nacl_storage.py, tests/test_redis_storage.py
Fixes #272 .
This is a relatively naive approach on patching the issue and there probably should be a more general/broad look into it design wise at some point. 
The reason I chose this solution is that it effectively patches the vulnerability without altering the library's behavior (i.e. what is saved in the database).
=> Patch Session Fixation in Redis Storage

aiohttp_session/__init__.py, demo/login_required_example.py, docs/reference.rst, tests/test_get_session.py
Closes #281 .
Implements new_session functionality,
Update documentation to include new function.
Update demo code to use new_session for login view.
=> Implement new_session functionality

docs/conf.py
Currently in http://aiohttp-session.readthedocs.io/en/latest/, the badges are saying "unknown".
With this fix, it will show the correct badges:
=> Fix the travis build badge and codecov badge in the docs

aiohttp_session/nacl_storage.py, docs/reference.rst, tests/test_nacl_storage.py
=> Fix NaClCookieStorage for corrupt cookie generating error 500

aiohttp_session/cookie_storage.py, tests/test_encrypted_cookie_storage.py
=> Patch Session Expiry for EncryptedCookieStorage

aiohttp_session/__init__.py, tests/test_nacl_storage.py
=> Empty session data if session age > max_age

README.rst
It has moved from travis-ci.org to travis-ci.com
Update the Travis CI badge in readme. Currently it is not rendered.
With this fix, readers can see the proper travis CI badge in readme.
None
* The format is `<Name> <Surname>`.
* Please keep alphabetical order, the file is sorted by names. 
* Make sure to use full sentences with correct case and punctuation, for …
=> Fix travis CI badge

CHANGES.txt, aiohttp_session/__init__.py
To address pending deprecation warning.
Instead of importing from collections, import from collections.abc
Users in 3.7+ would see deprecation warning:
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```
With this change, the deprecation warning disappears in Python 3.7.1+
* The format is `<Name> <Surname>`.
* Please keep alphabetical order, the file is sorted by names. 
* `.removal`: Signifying a …
=> import from collections.abc instead of from collections.

aiohttp_session/redis_storage.py, demo/redis_storage.py, requirements-dev.txt, tests/conftest.py, tests/test_redis_storage.py
=> Upgrade to aioredis 2

.github/workflows/ci.yaml
@webknjaz Do you want to setup the release env? I've tested this on aiohttp-devtools and it works.
Although, worth noting that I ran the deploy in the wrong environment first time and the CI says the deploy was a success despite it not uploading to pyPI.
=> Use release environment for deploy

.github/workflows/ci.yaml, setup.py
Drop 3.8 from CI and setup.py
Should not affect users, but officially 3.8 will not be supported.
=> Drop 3.8 support

.flake8, .github/workflows/codeql.yml, .pre-commit-config.yaml, aiohttp_session/redis_storage.py, demo/flash_messages_example.py, demo/login_required_example.py, demo/redis_storage.py, tests/conftest.py, tests/test_encrypted_cookie_storage.py, tests/test_get_session.py, tests/test_http_exception.py, tests/test_nacl_storage.py, tests/test_redis_storage.py
* Updates isort and flake8 to fix `pre-commit run`
* Fix flake8 error: long lines, unused imports, etc.
* Fix formatting of some files
Should not be any changes for the user
-
=> Fix CI: update isort and flake8 for pre-commit and format files

docs/conf.py
The old `intersphinx_mapping` format has been removed; it must now map identifiers to (target, inventory) tuples.
No.
- [N/A] Unit tests for the changes exist
=> Port to Sphinx 8.0
